version: "3"
services:
  server:
    image: wassimmalleh/task-manager:2.0
    container_name: server
    restart: on-failure:5 
    ports:
      - 4000:4000
    depends_on:
      - mongo
      - rabbitmq
      - redis
  client:
    image: wassimmalleh/task-manager-client:2.1
    container_name: client
    restart: on-failure:5 
    ports:
      - 80:80
    depends_on:
      - server
  mongo:
    image: mongo
    restart: on-failure:5 
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: on-failure:5 
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER : mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
  rabbitmq:
    image: "rabbitmq:3.11.7-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/data"
  redis:
    image: redis
    container_name: redis
    restart: on-failure:5 
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
volumes:
  rabbitmq_data:
  mongodb:
  cache:
    driver: local
