export const MANAGER = "Manager"
export const TECHNICIAN = "Technician"
export const PROTECTED = "PROTECTED"
export const GUEST = "GUEST"
export const NOTIFICATIONS_QUEUE = "Notifications"
export const NOTIFICATIONS_COUNT_DESCREASE = "NotificationsCount"
