apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: wassimmalleh/task-manager:2.0
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mongo-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mongo-password
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: mongo-url
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "1"